/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillageRouteImport } from './routes/village'
import { Route as SymptomRouteImport } from './routes/symptom'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as MedicineGuideRouteImport } from './routes/medicine-guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthReportRouteImport } from './routes/health-report'
import { Route as FamilyCareRouteImport } from './routes/family-care'
import { Route as DiseaseAnalyzerRouteImport } from './routes/disease-analyzer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AdminSmsRouteImport } from './routes/admin-sms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VillageIdRouteImport } from './routes/village.$id'
import { Route as FamilyCareIdRouteImport } from './routes/family-care.$id'

const VillageRoute = VillageRouteImport.update({
  id: '/village',
  path: '/village',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomRoute = SymptomRouteImport.update({
  id: '/symptom',
  path: '/symptom',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineGuideRoute = MedicineGuideRouteImport.update({
  id: '/medicine-guide',
  path: '/medicine-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReportRoute = HealthReportRouteImport.update({
  id: '/health-report',
  path: '/health-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyCareRoute = FamilyCareRouteImport.update({
  id: '/family-care',
  path: '/family-care',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseAnalyzerRoute = DiseaseAnalyzerRouteImport.update({
  id: '/disease-analyzer',
  path: '/disease-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/admin-sms',
  path: '/admin-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillageIdRoute = VillageIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VillageRoute,
} as any)
const FamilyCareIdRoute = FamilyCareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FamilyCareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-sms': typeof AdminSmsRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/disease-analyzer': typeof DiseaseAnalyzerRoute
  '/family-care': typeof FamilyCareRouteWithChildren
  '/health-report': typeof HealthReportRoute
  '/login': typeof LoginRoute
  '/medicine-guide': typeof MedicineGuideRoute
  '/records': typeof RecordsRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
  '/symptom': typeof SymptomRoute
  '/village': typeof VillageRouteWithChildren
  '/family-care/$id': typeof FamilyCareIdRoute
  '/village/$id': typeof VillageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-sms': typeof AdminSmsRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/disease-analyzer': typeof DiseaseAnalyzerRoute
  '/family-care': typeof FamilyCareRouteWithChildren
  '/health-report': typeof HealthReportRoute
  '/login': typeof LoginRoute
  '/medicine-guide': typeof MedicineGuideRoute
  '/records': typeof RecordsRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
  '/symptom': typeof SymptomRoute
  '/village': typeof VillageRouteWithChildren
  '/family-care/$id': typeof FamilyCareIdRoute
  '/village/$id': typeof VillageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-sms': typeof AdminSmsRoute
  '/appointments': typeof AppointmentsRoute
  '/dashboard': typeof DashboardRoute
  '/disease-analyzer': typeof DiseaseAnalyzerRoute
  '/family-care': typeof FamilyCareRouteWithChildren
  '/health-report': typeof HealthReportRoute
  '/login': typeof LoginRoute
  '/medicine-guide': typeof MedicineGuideRoute
  '/records': typeof RecordsRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
  '/symptom': typeof SymptomRoute
  '/village': typeof VillageRouteWithChildren
  '/family-care/$id': typeof FamilyCareIdRoute
  '/village/$id': typeof VillageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-sms'
    | '/appointments'
    | '/dashboard'
    | '/disease-analyzer'
    | '/family-care'
    | '/health-report'
    | '/login'
    | '/medicine-guide'
    | '/records'
    | '/signup'
    | '/sos'
    | '/symptom'
    | '/village'
    | '/family-care/$id'
    | '/village/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-sms'
    | '/appointments'
    | '/dashboard'
    | '/disease-analyzer'
    | '/family-care'
    | '/health-report'
    | '/login'
    | '/medicine-guide'
    | '/records'
    | '/signup'
    | '/sos'
    | '/symptom'
    | '/village'
    | '/family-care/$id'
    | '/village/$id'
  id:
    | '__root__'
    | '/'
    | '/admin-sms'
    | '/appointments'
    | '/dashboard'
    | '/disease-analyzer'
    | '/family-care'
    | '/health-report'
    | '/login'
    | '/medicine-guide'
    | '/records'
    | '/signup'
    | '/sos'
    | '/symptom'
    | '/village'
    | '/family-care/$id'
    | '/village/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  DashboardRoute: typeof DashboardRoute
  DiseaseAnalyzerRoute: typeof DiseaseAnalyzerRoute
  FamilyCareRoute: typeof FamilyCareRouteWithChildren
  HealthReportRoute: typeof HealthReportRoute
  LoginRoute: typeof LoginRoute
  MedicineGuideRoute: typeof MedicineGuideRoute
  RecordsRoute: typeof RecordsRoute
  SignupRoute: typeof SignupRoute
  SosRoute: typeof SosRoute
  SymptomRoute: typeof SymptomRoute
  VillageRoute: typeof VillageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/village': {
      id: '/village'
      path: '/village'
      fullPath: '/village'
      preLoaderRoute: typeof VillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom': {
      id: '/symptom'
      path: '/symptom'
      fullPath: '/symptom'
      preLoaderRoute: typeof SymptomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine-guide': {
      id: '/medicine-guide'
      path: '/medicine-guide'
      fullPath: '/medicine-guide'
      preLoaderRoute: typeof MedicineGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-report': {
      id: '/health-report'
      path: '/health-report'
      fullPath: '/health-report'
      preLoaderRoute: typeof HealthReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-care': {
      id: '/family-care'
      path: '/family-care'
      fullPath: '/family-care'
      preLoaderRoute: typeof FamilyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-analyzer': {
      id: '/disease-analyzer'
      path: '/disease-analyzer'
      fullPath: '/disease-analyzer'
      preLoaderRoute: typeof DiseaseAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-sms': {
      id: '/admin-sms'
      path: '/admin-sms'
      fullPath: '/admin-sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/village/$id': {
      id: '/village/$id'
      path: '/$id'
      fullPath: '/village/$id'
      preLoaderRoute: typeof VillageIdRouteImport
      parentRoute: typeof VillageRoute
    }
    '/family-care/$id': {
      id: '/family-care/$id'
      path: '/$id'
      fullPath: '/family-care/$id'
      preLoaderRoute: typeof FamilyCareIdRouteImport
      parentRoute: typeof FamilyCareRoute
    }
  }
}

interface FamilyCareRouteChildren {
  FamilyCareIdRoute: typeof FamilyCareIdRoute
}

const FamilyCareRouteChildren: FamilyCareRouteChildren = {
  FamilyCareIdRoute: FamilyCareIdRoute,
}

const FamilyCareRouteWithChildren = FamilyCareRoute._addFileChildren(
  FamilyCareRouteChildren,
)

interface VillageRouteChildren {
  VillageIdRoute: typeof VillageIdRoute
}

const VillageRouteChildren: VillageRouteChildren = {
  VillageIdRoute: VillageIdRoute,
}

const VillageRouteWithChildren =
  VillageRoute._addFileChildren(VillageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSmsRoute: AdminSmsRoute,
  AppointmentsRoute: AppointmentsRoute,
  DashboardRoute: DashboardRoute,
  DiseaseAnalyzerRoute: DiseaseAnalyzerRoute,
  FamilyCareRoute: FamilyCareRouteWithChildren,
  HealthReportRoute: HealthReportRoute,
  LoginRoute: LoginRoute,
  MedicineGuideRoute: MedicineGuideRoute,
  RecordsRoute: RecordsRoute,
  SignupRoute: SignupRoute,
  SosRoute: SosRoute,
  SymptomRoute: SymptomRoute,
  VillageRoute: VillageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
